#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"
MODEL=""; ORIGINAL_ARGS=("$@"); STRUCTURE="${REPO_ROOT}/structures/argon_fcc_4.lammps"; ELEMENTS="Ar"; TEMPERATURE="300"; STEPS="2000"; TIMESTEP="5.0e-4"; OUTPUT_DIR=""; LMP_BIN_ARG=""; GNNP_ROOT_ARG=""; DRY_RUN=0
usage() { cat <<'EOF'
Usage: bash scripts/run_demo.sh --model MODEL [options]
Options:
  --structure PATH       LAMMPS data file.
  --elements "Na Cl"     Elements in atom-type order.
  --temperature K        NVT temperature (default 300).
  --steps N              MD steps (default 2000).
  --timestep PS          Metal-unit timestep (default 5.0e-4).
  --output-dir PATH      Output directory.
  --lmp-bin PATH         LAMMPS binary override.
  --gnnp-root PATH       ML-GNNP directory override.
  --dry-run              Generate input and provenance only.
EOF
}
while (($#)); do
  case "$1" in
    --model) require_value "$1" "${2:-}"; MODEL="$2"; shift 2 ;;
    --structure) require_value "$1" "${2:-}"; STRUCTURE="$2"; shift 2 ;;
    --elements) require_value "$1" "${2:-}"; ELEMENTS="$2"; shift 2 ;;
    --temperature) require_value "$1" "${2:-}"; TEMPERATURE="$2"; shift 2 ;;
    --steps) require_value "$1" "${2:-}"; STEPS="$2"; shift 2 ;;
    --timestep) require_value "$1" "${2:-}"; TIMESTEP="$2"; shift 2 ;;
    --output-dir) require_value "$1" "${2:-}"; OUTPUT_DIR="$2"; shift 2 ;;
    --lmp-bin) require_value "$1" "${2:-}"; LMP_BIN_ARG="$2"; shift 2 ;;
    --gnnp-root) require_value "$1" "${2:-}"; GNNP_ROOT_ARG="$2"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option '$1'" ;;
  esac
done
[[ -n "${MODEL}" ]] || die "--model is required"
[[ -f "${STRUCTURE}" ]] || die "structure file not found: ${STRUCTURE}"
[[ "${TEMPERATURE}" =~ ^[0-9]+([.][0-9]+)?$ ]] || die "temperature must be numeric"
[[ "${STEPS}" =~ ^[0-9]+$ ]] || die "steps must be a positive integer"
((STEPS > 0)) || die "steps must be greater than zero"
[[ "${TIMESTEP}" =~ ^[0-9]+([.][0-9]+)?([eE][-+]?[0-9]+)?$ ]] || die "timestep must be numeric"
load_model "${MODEL}"
ATOM_TYPES="$(awk '$2 == "atom" && $3 == "types" { print $1; exit }' "${STRUCTURE}")"
[[ -n "${ATOM_TYPES}" ]] || die "could not read 'atom types' from ${STRUCTURE}"
read -r -a ELEMENT_ARRAY <<< "${ELEMENTS}"
((${#ELEMENT_ARRAY[@]} == ATOM_TYPES)) || die "structure has ${ATOM_TYPES} atom types but ${#ELEMENT_ARRAY[@]} elements were supplied"
if [[ -z "${OUTPUT_DIR}" ]]; then OUTPUT_DIR="${REPO_ROOT}/runs/${MODEL}_$(date +%Y%m%d-%H%M%S)"; fi
mkdir -p "${OUTPUT_DIR}"; OUTPUT_DIR="$(cd "${OUTPUT_DIR}" && pwd)"; STRUCTURE="$(cd "$(dirname "${STRUCTURE}")" && pwd)/$(basename "${STRUCTURE}")"
GNNP_PATH=""; LMP_PATH=""
if ((DRY_RUN == 0)); then
  GNNP_PATH="$(resolve_gnnp_root "${GNNP_ROOT_ARG}")" || die "ML-GNNP path not configured. Use config.env or --gnnp-root."
  LMP_PATH="$(resolve_lmp_bin "${LMP_BIN_ARG}")" || die "LAMMPS binary not configured. Set ${MODEL_BINARY_ENV} or use --lmp-bin."
  bash "${SCRIPT_DIR}/doctor.sh" --model "${MODEL}" --lmp-bin "${LMP_PATH}" --gnnp-root "${GNNP_PATH}"
else
  GNNP_PATH="${GNNP_ROOT_ARG:-${GNNP_ROOT:-/path/to/lammps/src/ML-GNNP}}"
  LMP_PATH="${LMP_BIN_ARG:-${!MODEL_BINARY_ENV:-/path/to/model-specific/lmp}}"
fi
INPUT_FILE="${OUTPUT_DIR}/run.in"; LOG_FILE="${OUTPUT_DIR}/log.lammps"; TRAJECTORY_FILE="${OUTPUT_DIR}/trajectory.lammpstrj"
cat > "${INPUT_FILE}" <<EOF
# Generated by scripts/run_demo.sh
units         metal
boundary      p p p
atom_style    atomic
log           ${LOG_FILE}
pair_style    gnnp ${GNNP_PATH}
read_data     ${STRUCTURE}
pair_coeff    * * ${MODEL_PAIR_PAYLOAD} ${ELEMENTS}
dump          trajectory all custom 10 ${TRAJECTORY_FILE} id element x y z
dump_modify   trajectory sort id element ${ELEMENTS}
thermo_style  custom step time temp pe ke etotal press vol
thermo        10
velocity      all create ${TEMPERATURE} 12345 mom yes rot yes dist gaussian
fix           thermostat all nvt temp ${TEMPERATURE} ${TEMPERATURE} 0.1
timestep      ${TIMESTEP}
run           ${STEPS}
EOF
{
  printf 'model_id=%s\n' "${MODEL_ID}"; printf 'model_name=%s\n' "${MODEL_NAME}"; printf 'model_status=%s\n' "${MODEL_STATUS}"; printf 'pair_payload=%s\n' "${MODEL_PAIR_PAYLOAD}"; printf 'conda_environment=%s\n' "${MODEL_ENV}"; printf 'lammps_binary=%s\n' "${LMP_PATH}"; printf 'gnnp_root=%s\n' "${GNNP_PATH}"; printf 'structure=%s\n' "${STRUCTURE}"; printf 'structure_sha256=%s\n' "$(sha256sum "${STRUCTURE}" | awk '{print $1}')"; printf 'elements=%s\n' "${ELEMENTS}"; printf 'temperature_K=%s\n' "${TEMPERATURE}"; printf 'steps=%s\n' "${STEPS}"; printf 'timestep_ps=%s\n' "${TIMESTEP}"; printf 'created_utc=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "${OUTPUT_DIR}/provenance.txt"
printf 'bash scripts/run_demo.sh' > "${OUTPUT_DIR}/command.txt"; printf ' %q' "${ORIGINAL_ARGS[@]}" >> "${OUTPUT_DIR}/command.txt"; printf '\n' >> "${OUTPUT_DIR}/command.txt"
printf 'Prepared %s\n' "${OUTPUT_DIR}"
if ((DRY_RUN)); then printf 'Dry run complete. Generated input: %s\n' "${INPUT_FILE}"; exit 0; fi
printf 'Launching %s with %s\n' "${MODEL_NAME}" "${LMP_PATH}"
if [[ "${MODEL_ENV}" == "base" ]]; then (cd "${OUTPUT_DIR}"; "${LMP_PATH}" -in "${INPUT_FILE}"); else (cd "${OUTPUT_DIR}"; conda run -n "${MODEL_ENV}" "${LMP_PATH}" -in "${INPUT_FILE}"); fi
python "${SCRIPT_DIR}/summarise_run.py" --log "${LOG_FILE}" --output-dir "${OUTPUT_DIR}" || printf 'WARNING: summary generation failed\n' >&2
printf 'Run complete: %s\n' "${OUTPUT_DIR}"
